name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - seaborn
  - plotly
  - ipywidgets
  - WordCloud
  - scikit-learn
